import {StyleSheet} from 'react-native';

import theme from '../../utils/theme';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    // justifyContent: 'center',
    backgroundColor: theme.WHITE_COLOR,
    marginTop: 30,
  },
  scrollView: {
    flex: 1,
    position: 'relative',
    paddingTop: 70,
    // paddingBottom: 150,
    // padding: theme.PAD_HR,
  },
  headerContainer: {
    height: 180,
    backgroundColor: theme.PRIMARY_COLOR_MONO,
    position: 'absolute',
  },
  roundContainer: {
    marginTop: -190,
    marginLeft: -100,
    height: theme.WIDTH_100 + 150,
    width: theme.WIDTH_100 + 150,
    borderRadius: theme.CIRCLE_BORDER_RADIUS + 400,
    backgroundColor: theme.PRIMARY_COLOR,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  logoBackground: {
    height: 350,
    tintColor: theme.PRIMARY_COLOR,
    resizeMode: 'center',
    alignSelf: 'center',
    marginLeft: 30,
    marginBottom: -18,
  },
  chartContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.WHITE_COLOR,
    marginHorizontal: theme.PAD_HR,
    borderRadius: theme.BORDER_IMAGE,
    overflow: 'hidden',
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.PRIMARY_COLOR,
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 20,
  },
  chartStyle: {
    paddingHorizontal: 0,
    marginHorizontal: theme.PAD_HR,
    borderRadius: theme.BORDER_IMAGE,
    borderWidth: 2,
  },
  chartInnerStyle: {
    alignItems: 'center',
    borderRadius: theme.BORDER_IMAGE,
    marginHorizontal: 'auto',
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.PRIMARY_COLOR,
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 20,
    marginBottom: 30,
  },
  filterContainer: {
    paddingLeft: theme.PAD_HR - 5,
    paddingHorizontal: theme.PAD_HR + 10,
    marginTop: 0,
    marginBottom: 15,
  },
  filterContainer2: {
    marginTop: 6,
    marginHorizontal: theme.PAD_HR,
  },
  circleTheme: {
    position: 'absolute',
    height: 250,
    width: 250,
    backgroundColor: theme.LIGHT_BLUE,
    borderRadius: theme.CIRCLE_BORDER_RADIUS + 100,
    top: -100,
    left: -30,
  },
  detailsContainer: {
    marginHorizontal: theme.PAD_HR,
    // marginTop: 8,
    marginVertical: 18,
    marginBottom: 180,
    borderRadius: theme.BORDER_IMAGE + 6,
    backgroundColor: theme.WHITE_COLOR,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.DARK_GREY,
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 4,
    paddingVertical: 14,
    paddingHorizontal: 8,
    // maxHeight: 340,
    overflow: 'hidden',
  },
});

export default styles;
