import {StyleSheet} from 'react-native';
import theme from '../../utils/theme';

const styles = StyleSheet.create({
  tabBar: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    // marginHorizontal: theme.PAD_HR,
    width: theme.WIDTH_100 * 0.93,
    position: 'absolute',
    bottom: theme.PAD_HR + 2,
    paddingHorizontal: 8,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: theme.WHITE_COLOR,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowColor: theme.PRIMARY_COLOR,
    shadowRadius: 8,
    elevation: 10,
    alignSelf: 'center',
    backfaceVisibility: 'hidden',
  },
  tabTab: {
    justifyContent: 'center',
    // width: 50,
    flexWrap: 'nowrap',
    alignItems: 'center',
    overflow: 'hidden',
    paddingVertical: 5.5,
  },
  tabTabSelected: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.PRIMARY_COLOR,
    paddingHorizontal: 4,
    borderRadius: theme.BORDER_IMAGE,
    // width: 95,
    flexWrap: 'nowrap',
    overflow: 'hidden',
  },
  tabTabText: {
    fontSize: theme.FONT_SIZE_EXTRA_SMALL - 3,
    color: theme.SECONDARY_COLOR,
    fontWeight: theme.FONT_WEIGHT_BOLD,
    marginTop: 1,
    flexWrap: 'nowrap',
    display: 'none',
  },
  tabTabTextSelected: {
    fontSize: theme.FONT_SIZE_EXTRA_SMALL - 3,
    color: theme.WHITE_COLOR,
    fontWeight: theme.FONT_WEIGHT_BOLD,
    marginTop: 1.5,
    flexWrap: 'nowrap',
    marginLeft: 6,
  },
  circleTheme: {
    backgroundColor: theme.LIGHT_BLUE,
    height: 30,
    width: 30,
    borderRadius: theme.CIRCLE_BORDER_RADIUS + 20,
    position: 'absolute',
    bottom: -10,
    left: -13,
  },
});

export default styles;
